#!/pro/bin/perl

# Increment the test count if CORE aded a global configuration variable
# that might influence binary compatability

use 5.018002;
use warnings;

my $n = 0 + shift // 1;

foreach my $tf (sort glob "t/[2-9]*.t") {
    open my $fh, "<", $tf or die "$tf: $!\n";
    local $/;
    my $t = <$fh>;
    close $fh;
    $t =~ s/\$tests = \K(\d+)/$1 + $n/e or next;
    open $fh, ">", $tf or die "$tf: $!\n";
    print $fh $t;
    close $fh;
    }
